### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by CiralaDevelopment** [Tobias-Glimmerfors/SearchEnginesProject#1]
Ny
---
- [x] Använd historik i sökningar
- [x] Spara profil
- [x] Spara klickade resultat i profil
- [x] Spara relevanceFeedback i profil
- [x] Använd klickade resultat i MoreLikeThis på varje query
- [x] Använd relevanta resultat i MoreLikeThis på varje query
- [ ] Ranking Evaluation i elastic
- [ ] Testomgång Rikard
- [ ] Testomgång Pontus
- [ ] Testomgång Tobias

Gammal
---
- [x] "Låna" kursens GUI
Spåra klick -> profilen

- [ ] Användarprofil
Sökhistorik
Besökshistorik
(Positiv/negativ feedback)

- [ ] Engine
ResultatObjekt -> PostingsList

- [ ] Searcher (query + profil)
Resultat -> ResultatObjekt

- [ ] Rapport

1. Sök i GUI
2. Query tas emot i engine
2a. Profilgrejer
3. Skickas till searcher

1. Resultat från elastic
2. Skickas som objekt till engine
3. Engine gör om till PostingsEntries
